apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-challenge
data:
  PORT_GATEWAY: "3000"
  PORT_USER_SERVICE: "3001"
  USER_SERVICE_URL: "http://user-service:3001"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "supersecret"
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://admin:p4ssw0rd@db:5432/app"
